import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { PrimaryButton, Screen, SecondaryButton, StatusPill } from '@/components/CicUI';

export default function PolicyDetailScreen() {
  const colors = useColors();
  const { id } = useLocalSearchParams();
  const { policies } = useApp();
  const policy = policies.find((item) => item.id === id);
  if (!policy) return <Screen><Text style={{ color: colors.foreground, fontFamily: 'Inter_700Bold', fontSize: 21 }}>Policy not found</Text><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_400Regular', marginTop: 8 }}>This policy may have been removed from this device.</Text></Screen>;
  return <Screen><Pressable onPress={() => router.back()} accessibilityRole="button" style={{ flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 24 }}><Feather name="arrow-left" size={18} color={colors.foreground} /><Text style={{ color: colors.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 14 }}>Back</Text></Pressable><View style={{ backgroundColor: colors.navy, borderRadius: 24, padding: 21, marginBottom: 22 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View style={{ width: 47, height: 47, borderRadius: 15, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }}><Feather name="shield" size={23} color="#FFFFFF" /></View><StatusPill status={policy.status} /></View><Text style={{ color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 23, lineHeight: 29, marginTop: 20, maxWidth: 300 }}>{policy.name}</Text><Text style={{ color: '#B9C1BD', fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 8 }}>{policy.id}  ·  Member {policy.member}</Text><View style={{ flexDirection: 'row', marginTop: 22, gap: 26 }}><View><Text style={{ color: '#94A09A', fontFamily: 'Inter_500Medium', fontSize: 11 }}>PREMIUM</Text><Text style={{ color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 18, marginTop: 4 }}>KSh {policy.premium.toLocaleString()}</Text></View><View><Text style={{ color: '#94A09A', fontFamily: 'Inter_500Medium', fontSize: 11 }}>RENEWS</Text><Text style={{ color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 15, marginTop: 6 }}>{policy.endDate}</Text></View></View></View><Text style={{ color: colors.foreground, fontFamily: 'Inter_700Bold', fontSize: 18, marginBottom: 13 }}>What’s included</Text><View style={{ backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 19, padding: 16, marginBottom: 23 }}>{policy.benefits.map((benefit) => <View key={benefit} style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 }}><View style={{ width: 23, height: 23, borderRadius: 8, backgroundColor: colors.successSoft, alignItems: 'center', justifyContent: 'center' }}><Feather name="check" size={14} color={colors.success} /></View><Text style={{ color: colors.inkSoft, fontFamily: 'Inter_500Medium', fontSize: 13, flex: 1 }}>{benefit}</Text></View>)}</View><PrimaryButton title="Report a claim" onPress={() => router.push(`/claim/new?policyId=${policy.id}`)} icon="file-plus" /><View style={{ marginTop: 11 }}><SecondaryButton title="View all policies" onPress={() => router.push('/policies')} icon="layers" /></View></Screen>;
}
